ood_dataset:
  name: mstar3_seed1_osr
  num_classes: 3
  pre_size: 64
  image_size: 64

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 12
  shuffle: True

  split_names: [val, osr]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_mstar3/val/val_mstar10_3_seed1.txt
  osr:
    datasets: [mstar7]
    mstar7:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/osr_mstar3/test/test_mstar10_7_ood_seed1.txt
